import type { CreateTemplate } from "@/lib/learning/types";

export const CREATE_TEMPLATES: CreateTemplate[] = [
  {
    id: "product-teardown",
    title: "Product Teardown",
    blurb: "Dissect a live product: who it's for, what works, where it frictions, what you'd change.",
    howItWorks:
      "Pick one product you use. Fill sections top-to-bottom. Stay specific — screens, flows, and moments — not brand slogans. End with one opportunity and one metric.",
    starterTips: [
      "Choose a product you can open right now and click through.",
      "Write friction as a user moment: “When I ___, I can’t ___.”",
      "One opportunity > five vague ideas.",
    ],
    competencies: ["product-critique", "user-segmentation", "pain-points", "north-star-metrics"],
    relatedLessonIds: ["lesson-segmentation", "lesson-user-problem", "lesson-choose-metrics"],
    sections: [
      { id: "product", label: "Product", placeholder: "What are you analyzing?" },
      { id: "user", label: "User", placeholder: "Who is it primarily for?" },
      { id: "jtbd", label: "Job to be done", placeholder: "What problem is it solving, in their words?" },
      { id: "core", label: "Core experience", placeholder: "How does the product solve it today?" },
      { id: "works", label: "What works", placeholder: "Strengths — be specific." },
      { id: "friction", label: "Friction", placeholder: "Weaknesses / pain points." },
      { id: "opportunity", label: "Opportunity", placeholder: "What would you improve first, and why?" },
      { id: "metric", label: "Metric", placeholder: "How would you know the improvement worked?" },
    ],
    exampleFill: {
      product: "CampusEvents — a student club event discovery app (fictional).",
      user: "First-year undergrads who want to find clubs in weeks 1–4.",
      jtbd: "When I’m new on campus, help me find events I’d actually enjoy tonight — without scrolling five GroupMes.",
      core: "Feed of events + club pages + “going” RSVP.",
      works: "Clean card UI; filters by day; club logos make browsing fast.",
      friction: "When two clubs post the same time, I can’t compare travel time or friend overlap.",
      opportunity: "Add “friends going” + campus map ETA on the event card for the first-week cohort.",
      metric: "Week-1 → Week-3 % of first-years who RSVP to ≥2 events.",
    },
  },
  {
    id: "feature-proposal",
    title: "Feature Proposal",
    blurb: "Turn a problem into a concrete feature pitch with tradeoffs and success metrics.",
    howItWorks:
      "Start with the problem and segment. Pitch one feature, then force yourself through alternatives and tradeoffs before metrics. Don’t invent fake research — mark assumptions.",
    starterTips: [
      "If the problem statement contains your feature, rewrite it.",
      "Name at least two alternatives you rejected.",
      "Pick one primary metric and one guardrail.",
    ],
    competencies: ["user-problems", "user-segmentation", "prioritization", "feature-ideation", "north-star-metrics"],
    relatedLessonIds: [
      "lesson-user-problem",
      "lesson-segmentation",
      "lesson-prioritize",
      "lesson-choose-metrics",
    ],
    sections: [
      { id: "problem", label: "Problem", placeholder: "Who struggles, when, and what's broken today?" },
      { id: "targetUser", label: "Target user", placeholder: "Which segment are you designing for?" },
      { id: "evidence", label: "Evidence / assumptions", placeholder: "What do you know vs. what are you assuming?" },
      { id: "proposal", label: "Proposed feature", placeholder: "Describe the change without inventing fake research." },
      { id: "flow", label: "User flow", placeholder: "Key steps from trigger to value." },
      { id: "alternatives", label: "Alternatives", placeholder: "What else did you consider?" },
      { id: "tradeoffs", label: "Tradeoffs", placeholder: "What do you give up by choosing this?" },
      { id: "metrics", label: "Success metrics", placeholder: "Primary metric + guardrails." },
      { id: "risks", label: "Risks", placeholder: "What could go wrong?" },
      { id: "next", label: "Next steps", placeholder: "How would you validate or ship this?" },
    ],
    exampleFill: {
      problem:
        "When clubs post across Instagram + Discord, first-years miss events they’d attend — so early belonging drops.",
      targetUser: "First-year students living on campus, weeks 1–4.",
      evidence:
        "Assumption: discovery is the bottleneck (not interest). Known: support tickets mention “I didn’t know it was tonight.”",
      proposal: "Tonight digest: push + in-app list of 5 events within 20 min walk, personalized by club follows.",
      flow: "5pm trigger → digest → tap event → RSVP → calendar add.",
      alternatives: "Better search only; campus map heat layer; club ambassador DMs.",
      tradeoffs: "Push fatigue risk; eng cost for personalization vs. a static “happening tonight” list.",
      metrics: "Primary: RSVPs from digest. Guardrail: push opt-out rate.",
      risks: "Spam perception; cold-start with few follows.",
      next: "Ship static tonight list first; A/B personalization later if open rates hold.",
    },
  },
  {
    id: "zero-to-one",
    title: "0 → 1 Product",
    blurb: "Frame a new product bet: insight, MVP, prioritization, and how you'd validate.",
    howItWorks:
      "You’re pitching a new bet, not a feature on an existing roadmap. Nail the insight and the MVP that tests it. Explicitly list what’s out of v1.",
    starterTips: [
      "Insight ≠ slogan. Make it falsifiable.",
      "MVP should test the insight — not a mini version of the dream product.",
      "Write kill criteria before you fall in love with the idea.",
    ],
    competencies: ["zero-to-one", "user-problems", "positioning", "prioritization", "experimentation"],
    relatedLessonIds: ["lesson-product-sense", "lesson-strategy-tradeoffs", "lesson-prioritize"],
    sections: [
      { id: "problemSpace", label: "Problem space", placeholder: "What territory are you exploring?" },
      { id: "targetUser", label: "Target user", placeholder: "Who feels this most acutely?" },
      { id: "alternatives", label: "Current alternatives", placeholder: "How do they cope today?" },
      { id: "insight", label: "Insight", placeholder: "What non-obvious truth unlocks a better approach?" },
      { id: "valueProp", label: "Value proposition", placeholder: "Why you, why now?" },
      { id: "core", label: "Core experience", placeholder: "The one experience that must feel magical." },
      { id: "mvp", label: "MVP", placeholder: "Smallest shippable version that tests the insight." },
      { id: "prioritization", label: "Prioritization", placeholder: "What is explicitly out of v1?" },
      { id: "metrics", label: "Metrics", placeholder: "How you'll know the bet is working." },
      { id: "risks", label: "Risks", placeholder: "Kill criteria and open risks." },
      { id: "validation", label: "Launch / validation plan", placeholder: "How you'll learn cheaply." },
    ],
    exampleFill: {
      problemSpace: "Student club organizers burning out on logistics vs. community.",
      targetUser: "Club presidents at mid-size universities running 2–4 events/month.",
      alternatives: "GroupMe + Google Forms + Venmo + Instagram — duct tape stack.",
      insight:
        "Organizers don’t need another “community app” — they need a single ops spine that makes the next event inevitable.",
      valueProp: "One place from “idea” → venue → RSVP → reminder → attendance — without five tools.",
      core: "Create event → auto checklist → member reminders that feel native to the club.",
      mvp: "Web-only event + checklist + SMS reminders for one club cohort.",
      prioritization: "Out of v1: payments, sponsorships, cross-campus discovery, AI chat.",
      metrics: "Events created / week; % events with ≥70% RSVP→show; organizer NPS.",
      risks: "Kill if organizers won’t leave GroupMe after 3 events. Risk: SMS cost.",
      validation: "10 presidents, 4 weeks, instrument checklist completion + show rates.",
    },
  },
  {
    id: "prd",
    title: "PRD",
    blurb: "A practical product requirements outline — not the one true PRD format.",
    howItWorks:
      "Write for eng + design: problem, goals, non-goals, requirements, stories, edge cases. Open questions stay open — don’t fake certainty.",
    starterTips: [
      "Non-goals prevent scope creep more than goals do.",
      "Requirements should be testable (“user can…”) not vibes.",
      "List edge cases before kickoff, not after QA.",
    ],
    competencies: ["user-problems", "goals", "working-with-engineering", "working-with-design"],
    relatedLessonIds: ["lesson-eng-design", "lesson-user-problem", "lesson-choose-metrics"],
    sections: [
      { id: "overview", label: "Overview", placeholder: "One paragraph on what this is." },
      { id: "problem", label: "Problem", placeholder: "Problem statement without the solution." },
      { id: "goals", label: "Goals", placeholder: "What success looks like." },
      { id: "nonGoals", label: "Non-goals", placeholder: "What this explicitly will not do." },
      { id: "users", label: "Users", placeholder: "Primary and secondary users." },
      { id: "requirements", label: "Requirements", placeholder: "Must-haves, clearly stated." },
      { id: "stories", label: "User stories", placeholder: "As a… I want… so that…" },
      { id: "edgeCases", label: "Edge cases", placeholder: "Weird paths and failure modes." },
      { id: "metrics", label: "Metrics", placeholder: "How you'll measure." },
      { id: "risks", label: "Risks", placeholder: "Technical, product, and go-to-market risks." },
      { id: "openQuestions", label: "Open questions", placeholder: "What still needs deciding." },
    ],
    exampleFill: {
      overview: "Add a “Tonight on campus” digest to CampusEvents for first-years.",
      problem: "First-years miss same-day events because discovery is fragmented.",
      goals: "Increase same-day RSVPs from first-years by 15% in 6 weeks.",
      nonGoals: "No full recommendation ML; no payments; no club admin redesign.",
      users: "Primary: first-years. Secondary: club organizers (content quality).",
      requirements:
        "5pm digest of ≤5 events within 20 min walk; RSVP from digest; opt-out; empty state if none.",
      stories:
        "As a first-year, I want a short tonight list so I can pick something without doomscrolling.",
      edgeCases: "No events tonight; location permission denied; user outside campus geofence.",
      metrics: "Digest→RSVP rate; opt-out; crash-free sessions.",
      risks: "Push fatigue; inaccurate walking time; sparse inventory early semester.",
      openQuestions: "SMS vs. push only? Who curates if inventory is low?",
    },
  },
  {
    id: "experiment-plan",
    title: "Experiment Plan",
    blurb: "Pre-commit hypothesis, metrics, and decision rules before you peek at results.",
    howItWorks:
      "Write the hypothesis and decision rule before results. Leave Results and Learnings blank until you have real data — honesty is the point.",
    starterTips: [
      "One primary metric. Guardrails protect what you refuse to break.",
      "Decision rule: ship / iterate / kill — with numbers.",
      "Don’t peek mid-test and “call it early” without a pre-written rule.",
    ],
    competencies: ["experimentation", "north-star-metrics", "decision-making", "launch-metrics"],
    relatedLessonIds: ["lesson-experimentation", "lesson-choose-metrics", "lesson-diagnose-drop"],
    sections: [
      { id: "hypothesis", label: "Hypothesis", placeholder: "If we… then… because…" },
      { id: "segment", label: "User / segment", placeholder: "Who is exposed?" },
      { id: "change", label: "Change", placeholder: "What exactly differs?" },
      { id: "primary", label: "Primary metric", placeholder: "The one number that decides." },
      { id: "guardrails", label: "Guardrail metrics", placeholder: "What must not get worse?" },
      { id: "design", label: "Experiment design", placeholder: "Assignment, duration, sample notes." },
      { id: "expected", label: "Expected result", placeholder: "What would surprise you?" },
      { id: "decision", label: "Decision rule", placeholder: "Ship / iterate / kill criteria." },
      { id: "results", label: "Results", placeholder: "Leave blank until you have real results." },
      { id: "learnings", label: "Learnings", placeholder: "Leave blank until after the experiment." },
    ],
    exampleFill: {
      hypothesis:
        "If we send a 5pm tonight digest, then same-day RSVPs rise because discovery timing is the bottleneck.",
      segment: "First-years with push enabled, weeks 1–4.",
      change: "50% get digest; 50% get status quo feed only.",
      primary: "Same-day RSVPs per user per week.",
      guardrails: "Push opt-out; session crashes; organizer complaint rate.",
      design: "2-week A/B; need ~X users (estimate with eng); no peeking day 3.",
      expected: "Lift if inventory ≥3 events/night; flat if campus is quiet.",
      decision: "Ship if +10% primary and opt-out <+2pp; else iterate copy or kill.",
      results: "",
      learnings: "",
    },
  },
  {
    id: "study-plan",
    title: "PM Study Plan",
    blurb: "Turn Weeks 1–3 into a personal plan: technical literacy, PM cores, and strengths stories.",
    howItWorks:
      "Personalize the Weeks 1–3 roadmap. Put hours next to each track. Prefer fewer resources used deeply over a bookmark graveyard.",
    starterTips: [
      "Name a recruiting goal with a date.",
      "Schedule technical + PM + strengths every week — parallel, not sequential.",
      "One weekly check-in metric: e.g. drills completed, stories rewritten.",
    ],
    competencies: ["study-planning", "technical-fluency", "prioritization", "non-technical-strengths"],
    relatedLessonIds: [
      "lesson-weeks-1-3-roadmap",
      "lesson-tech-literacy-basics",
      "lesson-coding-interview-reality",
    ],
    sections: [
      { id: "goal", label: "Recruiting goal", placeholder: "Roles / timeline you’re aiming for." },
      { id: "week1", label: "Week 1 focus", placeholder: "Technical + PM core + strengths block." },
      { id: "week2", label: "Week 2 focus", placeholder: "What you’ll deepen." },
      { id: "week3", label: "Week 3 focus", placeholder: "What you’ll rehearse for interviews." },
      { id: "technical", label: "Technical literacy plan", placeholder: "Docs, APIs, optional NeetCode cadence." },
      { id: "pmCores", label: "PM core drills", placeholder: "Sense, RICE/MoSCoW, OKRs/JTBD, research." },
      { id: "strengths", label: "Non-technical strengths", placeholder: "Stories you’ll translate into PM language." },
      { id: "resources", label: "External resources", placeholder: "Links you’ll actually use (not hoard)." },
      { id: "checkins", label: "Weekly check-in", placeholder: "How you’ll know the plan is working." },
    ],
    exampleFill: {
      goal: "APM / PM internship interviews in 8 weeks.",
      week1: "Tech: APIs + frontend/backend (2×25m). PM: RICE lesson + 1 drill. Strengths: draft 1 story.",
      week2: "Tech: one system-design lite read. PM: OKRs/JTBD + product sense drill. Strengths: revise story.",
      week3: "Mock closing questions aloud. 2 drills. Rehearse story with a timer.",
      technical: "MDN fetch overview + one public API walkthrough; optional 3 easy NeetCode/week.",
      pmCores: "Mon/Wed Practice Quick Drill; Fri Create feature proposal outline.",
      strengths: "Club ops leadership → prioritization under constraint; retail job → customer pain spotting.",
      resources: "Product Place Learn + Practice only this month; one external doc max.",
      checkins: "Sunday: drills done? stories updated? one tech concept explained out loud?",
    },
  },
  {
    id: "interview-prep",
    title: "Interview Prep Worksheet",
    blurb: "Closing questions, strength stories, and follow-ups — rehearsed in your voice.",
    howItWorks:
      "Rewrite the closing-question menu in your natural voice. Draft 2–3 strength stories with proof. Leave post-interview notes blank until after.",
    starterTips: [
      "Say closing questions out loud — awkward on paper is fine if it sounds like you.",
      "Strength stories need a decision, not a résumé bullet.",
      "Brave feedback questions only if rapport is real.",
    ],
    competencies: ["interview-closing", "interview-behavioral", "non-technical-strengths"],
    relatedLessonIds: [
      "lesson-interview-closing",
      "lesson-non-technical-strengths",
      "lesson-stakeholders",
    ],
    sections: [
      { id: "role", label: "Target role / company", placeholder: "What you’re interviewing for." },
      { id: "stories", label: "Strength stories", placeholder: "2–3 proof moments in STAR-ish form." },
      { id: "technical", label: "Technical talking points", placeholder: "Fluency notes — not a fake CS resume." },
      { id: "closing", label: "Closing questions (your wording)", placeholder: "Rewrite the menu in your natural voice." },
      { id: "success", label: "What success looks like (to ask)", placeholder: "Your phrasing + why you’ll ask it." },
      { id: "challenge", label: "Biggest challenge (to ask)", placeholder: "Your phrasing + how you’ll respond." },
      { id: "feedback", label: "Confidence / pause questions", placeholder: "Only if rapport allows — draft carefully." },
      { id: "culture", label: "Team / culture questions", placeholder: "Best-employee qualities; why they like it here." },
      { id: "followups", label: "Post-interview notes", placeholder: "Leave blank until after — no invented feedback." },
    ],
    exampleFill: {
      role: "PM intern — consumer mobile team (fictional Co).",
      stories:
        "1) Cut club event no-shows by adding day-of SMS — decision to kill a vanity redesign. 2) Mediated design/eng scope fight with a written non-goals list.",
      technical:
        "Can explain client/server/API; know what an A/B assignment means; honest about not claiming FAANG-level algorithms.",
      closing:
        "What would a strong intern nail in the first month? Where do new PMs usually stumble here?",
      success: "“What does great look like at 90 days?” — so I know how they score the internship.",
      challenge: "“What’s the hardest part of shipping on this team right now?” — listen for process vs. product risk.",
      feedback: "Optional: “Anything I can clarify that would raise your confidence?”",
      culture: "“What do your strongest PMs do differently week to week?” / “What keeps you here?”",
      followups: "",
    },
  },
];

export const CREATE_TEMPLATES_BY_ID = Object.fromEntries(
  CREATE_TEMPLATES.map((t) => [t.id, t]),
) as Record<string, CreateTemplate>;
