import type { PracticeQuestion } from "@/lib/learning/types";

/** Choice drills — tap answers instead of typing. Original Product Place content. */
export const PRACTICE_CHOICE_QUESTIONS: PracticeQuestion[] = [
  {
    id: "pq-mc-metric-first",
    title: "What to Check First",
    prompt:
      "Retention dropped 8% week-over-week after a release. What’s the best first move before proposing a fix?",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["diagnosing-metrics", "interview-execution"],
    relatedLessonIds: ["lesson-diagnose-drop"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: ["Data quality before solutions.", "Localize before inventing."],
    choices: [
      { id: "a", label: "Ship a retention feature based on a hunch." },
      { id: "b", label: "Confirm the metric definition, data quality, and where the drop localizes." },
      { id: "c", label: "Ask design for a full redesign of onboarding." },
      { id: "d", label: "Roll back the release immediately without checking segments." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Diagnosis before solution. Trust the number, then localize (platform, cohort, funnel step) before you invent fixes.",
  },
  {
    id: "pq-mc-north-star",
    title: "North-star Pick",
    prompt: "Which is the strongest north-star style metric for a marketplace that connects tutors and students?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["north-star-metrics", "goals"],
    relatedLessonIds: ["lesson-choose-metrics"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: ["Value exchange over vanity.", "Two-sided awareness."],
    choices: [
      { id: "a", label: "App downloads this week." },
      { id: "b", label: "Weekly completed tutoring sessions with a rating ≥ 4." },
      { id: "c", label: "Number of slides in the pitch deck." },
      { id: "d", label: "Total page views on the marketing site." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "North stars track the core value exchange. Completed rated sessions beat vanity traffic or downloads.",
  },
  {
    id: "pq-mc-segment",
    title: "Segmentation Instinct",
    prompt: "You’re designing campus event discovery. Which segmentation is most useful early?",
    category: "product-sense",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["user-segmentation", "user-problems"],
    relatedLessonIds: ["lesson-segmentation"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Behavior over demographics alone."],
    choices: [
      { id: "a", label: "Zodiac sign." },
      {
        id: "b",
        label: "Week-2 first-years hunting friends vs week-10 students protecting focus time.",
      },
      { id: "c", label: "Everyone who owns a phone." },
      { id: "d", label: "People who like the color blue." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Good segments map to different jobs and constraints — not cute demographics.",
  },
  {
    id: "pq-mc-api",
    title: "API in Plain Language",
    prompt: "Best way to explain an API to a non-engineer in an interview?",
    category: "technical",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["apis-systems", "technical-fluency"],
    relatedLessonIds: ["lesson-apis-frontend-backend"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Contract metaphor.", "No jargon dump."],
    choices: [
      { id: "a", label: "It’s when the frontend is written in React." },
      {
        id: "b",
        label: "A contract that lets one system request data or actions from another in a defined way.",
      },
      { id: "c", label: "The database itself." },
      { id: "d", label: "A design file in Figma." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "APIs are contracts between systems — request/response, not “the database” or “React.”",
  },
  {
    id: "pq-mc-prioritize",
    title: "Prioritization Call",
    prompt: "Eng can ship a hack in 3 days or a scalable fix in 3 weeks. What’s the PM move?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "multiple-choice",
    competencies: ["prioritization", "tradeoffs"],
    relatedLessonIds: ["lesson-prioritize", "lesson-strategy-tradeoffs"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Context over dogma.", "Write the decision down."],
    choices: [
      { id: "a", label: "Always pick the hack — speed wins forever." },
      { id: "b", label: "Always pick scalable — debt is never worth it." },
      {
        id: "c",
        label: "Decide from urgency, blast radius, and follow-up plan — then write the tradeoff and revisit date.",
      },
      { id: "d", label: "Flip a coin so the team feels involved." },
    ],
    correctChoiceIds: ["c"],
    choiceExplanation:
      "Tradeoffs are contextual. Name urgency, risk, and when you’ll pay down the hack.",
  },
  {
    id: "pq-mc-story",
    title: "Behavioral Story Core",
    prompt: "What’s the strongest spine for a behavioral answer?",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["interview-behavioral"],
    relatedLessonIds: ["lesson-non-technical-strengths"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: ["Decision + outcome."],
    choices: [
      { id: "a", label: "List every task you touched on the project." },
      {
        id: "b",
        label: "Situation → constraint → your decision → outcome → what you’d repeat.",
      },
      { id: "c", label: "Praise your manager for five minutes." },
      { id: "d", label: "Describe the company org chart." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Interviewers buy judgment. Constraint + decision + outcome beats a task dump.",
  },
  {
    id: "pq-mc-closing",
    title: "Strong Closer",
    prompt: "Which closing question best signals judgment without sounding interrogative?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["interview-closing", "interview-behavioral"],
    relatedLessonIds: ["lesson-interview-closing"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: ["Curiosity + bar."],
    choices: [
      { id: "a", label: "So… how much does this pay?" },
      { id: "b", label: "What does success in this role look like in the first 6 months?" },
      { id: "c", label: "Do you hate your job?" },
      { id: "d", label: "Can I leave early today?" },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Success criteria shows you’re already thinking like someone who’ll own outcomes.",
  },
  {
    id: "pq-mc-rice",
    title: "Rice Misuse",
    prompt: "What’s the most common RICE failure mode?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["rice-moscow", "prioritization"],
    relatedLessonIds: ["lesson-prioritize"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Scores are inputs."],
    choices: [
      { id: "a", label: "Treating the score as truth instead of a conversation starter." },
      { id: "b", label: "Writing down assumptions." },
      { id: "c", label: "Comparing relative effort." },
      { id: "d", label: "Talking to stakeholders about confidence." },
    ],
    correctChoiceIds: ["a"],
    choiceExplanation:
      "RICE is a discussion scaffold. Fake precision without shared assumptions is theater.",
  },
  {
    id: "pq-mc-b2b",
    title: "B2B Buyer vs User",
    prompt: "In B2B, what’s often true?",
    category: "strategy",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["product-business-models", "market-understanding"],
    relatedLessonIds: ["lesson-b2b-b2c-ai"],
    relatedCreateTemplateIds: ["product-teardown"],
    rubric: ["Buyer ≠ user."],
    choices: [
      { id: "a", label: "The buyer and daily user are always the same person." },
      {
        id: "b",
        label: "The economic buyer and the end user can have different jobs and success metrics.",
      },
      { id: "c", label: "Only designers talk to customers." },
      { id: "d", label: "Metrics never matter in B2B." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Buyer vs user split is the classic B2B trap — design for both jobs.",
  },
  {
    id: "pq-mc-experiment",
    title: "Experiment Goal",
    prompt: "A good A/B test primarily aims to…",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "multiple-choice",
    competencies: ["experimentation"],
    relatedLessonIds: ["lesson-experimentation"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: ["Learn, not prove ego."],
    choices: [
      { id: "a", label: "Confirm the PM was right all along." },
      {
        id: "b",
        label: "Reduce uncertainty about a decision with a clear primary metric and guardrails.",
      },
      { id: "c", label: "Ship as many variants as possible forever." },
      { id: "d", label: "Avoid talking to users." },
    ],
    correctChoiceIds: ["b"],
    choiceExplanation:
      "Experiments buy information. Primary metric + guardrails beat “prove me right.”",
  },
  // Checkbox / select-all
  {
    id: "pq-cb-diagnosis-steps",
    title: "Diagnosis Checklist",
    prompt: "Select all that belong in a solid metric-drop diagnosis before you propose a feature.",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "checkbox",
    competencies: ["diagnosing-metrics", "metric-trees"],
    relatedLessonIds: ["lesson-diagnose-drop", "lesson-metric-tree"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: ["Quality.", "Localize.", "Hypotheses."],
    choices: [
      { id: "a", label: "Verify metric definition and instrumentation." },
      { id: "b", label: "Jump straight to a redesign brief." },
      { id: "c", label: "Segment by platform, cohort, or funnel step." },
      { id: "d", label: "Check recent releases and incidents." },
      { id: "e", label: "Ignore seasonality and holidays." },
    ],
    correctChoiceIds: ["a", "c", "d"],
    choiceExplanation:
      "Trust → localize → context (releases) → then hypotheses. Redesign-first and ignoring seasonality are traps.",
  },
  {
    id: "pq-cb-story-strengths",
    title: "Non-tech Strengths",
    prompt: "Which of these can be real PM strengths from prior non-tech experience? Select all that apply.",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 3,
    format: "checkbox",
    competencies: ["interview-behavioral"],
    relatedLessonIds: ["lesson-non-technical-strengths"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: ["Translate strengths into decisions."],
    choices: [
      { id: "a", label: "Customer-facing empathy from service roles." },
      { id: "b", label: "Never mentioning your past because it isn’t “tech”." },
      { id: "c", label: "Consulting / business instincts about tradeoffs." },
      { id: "d", label: "Cross-functional thinking from design or ops." },
      { id: "e", label: "Claiming you’re unique without a proof story." },
    ],
    correctChoiceIds: ["a", "c", "d"],
    choiceExplanation:
      "Non-tech backgrounds are assets when tied to decisions. Hiding them — or adjective-only claims — wastes the interview.",
  },
  {
    id: "pq-cb-prd-bones",
    title: "Prd Must-haves",
    prompt: "Select all that usually belong in a useful early PRD / write-up.",
    category: "design-collab",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "checkbox",
    competencies: ["roadmapping", "role-of-pm"],
    relatedLessonIds: ["lesson-product-lifecycle"],
    relatedCreateTemplateIds: ["prd"],
    rubric: ["Problem before solution."],
    choices: [
      { id: "a", label: "Problem / opportunity and who feels it." },
      { id: "b", label: "Success metrics and guardrails." },
      { id: "c", label: "Pixel-perfect CSS for every state." },
      { id: "d", label: "Non-goals and open questions." },
      { id: "e", label: "A fake timeline with zero engineering input." },
    ],
    correctChoiceIds: ["a", "b", "d"],
    choiceExplanation:
      "Problem, metrics, non-goals, and open questions beat premature polish and fantasy dates.",
  },
  {
    id: "pq-cb-tradeoff",
    title: "Good Tradeoff Talk",
    prompt: "When you call a product tradeoff in an interview, select all that strengthen the answer.",
    category: "product-sense",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "checkbox",
    competencies: ["tradeoffs", "interview-product-sense"],
    relatedLessonIds: ["lesson-strategy-tradeoffs"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Explicit loser.", "Why now."],
    choices: [
      { id: "a", label: "Name what you are intentionally not optimizing." },
      { id: "b", label: "Pretend there is no downside." },
      { id: "c", label: "Say what you’d monitor after shipping." },
      { id: "d", label: "Explain why this choice fits the goal and constraint." },
      { id: "e", label: "Hide assumptions so you sound confident." },
    ],
    correctChoiceIds: ["a", "c", "d"],
    choiceExplanation:
      "Strong tradeoffs name the loser, the why, and the monitor — not fake certainty.",
  },
  {
    id: "pq-cb-tech-pm",
    title: "Technical Fluency Signals",
    prompt: "Select all that show healthy PM technical fluency (not engineer cosplay).",
    category: "technical",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "checkbox",
    competencies: ["technical-fluency", "apis-systems"],
    relatedLessonIds: ["lesson-apis-frontend-backend", "lesson-tech-literacy-basics"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: ["Ask better questions."],
    choices: [
      { id: "a", label: "Can explain FE vs BE ownership for a “simple” button." },
      { id: "b", label: "Memorizes every sorting algorithm." },
      { id: "c", label: "Asks about latency, failure modes, and instrumentation." },
      { id: "d", label: "Respects eng estimates and asks what cuts scope." },
      { id: "e", label: "Overrides architecture without context to look smart." },
    ],
    correctChoiceIds: ["a", "c", "d"],
    choiceExplanation:
      "Fluency is collaboration: systems intuition + good questions — not LeetCode flex or ego overrides.",
  },
  {
    id: "pq-cb-closing-menu",
    title: "Closing Question Menu",
    prompt: "Which closing questions are generally strong? Select all that apply.",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 4,
    format: "checkbox",
    competencies: ["interview-closing"],
    relatedLessonIds: ["lesson-interview-closing"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: ["Curiosity without interrogation."],
    choices: [
      {
        id: "a",
        label: "What qualities does your best person in this role demonstrate?",
      },
      { id: "b", label: "What do you think would be a challenge for me here?" },
      { id: "c", label: "Why didn’t you fire the last person?" },
      { id: "d", label: "What does success in this role look like?" },
      { id: "e", label: "Can you guarantee I’ll get the offer today?" },
    ],
    correctChoiceIds: ["a", "b", "d"],
    choiceExplanation:
      "Bar, challenge, and success criteria invite useful signal. Aggressive or demandy closers burn rapport.",
  },
];
