import type { PracticeQuestion } from "@/lib/learning/types";

/** Original Product Place practice prompts — not copied from any question bank. */
export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  {
    id: "pq-sense-campus-events",
    title: "Campus Event Discovery",
    prompt:
      "Design a feature that helps first-year college students discover campus events they would actually attend.",
    category: "product-sense",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["interview-product-sense", "user-segmentation", "feature-ideation", "user-problems"],
    relatedLessonIds: ["lesson-segmentation", "lesson-product-sense", "lesson-user-problem"],
    relatedCreateTemplateIds: ["feature-proposal"],
    hints: [
      "Who is the first-year student in week 2 vs week 10?",
      "Where do events live today, and why does that fail?",
    ],
    rubric: [
      "Clarify the goal.",
      "Define the user / segment.",
      "Describe the current pain.",
      "Generate multiple solution directions.",
      "Choose one with tradeoffs.",
      "Define success metrics.",
    ],
  },
  {
    id: "pq-sense-spotify-drop",
    title: "Listening Hours Investigation Framing",
    prompt:
      "You're a PM on a music streaming app. Daily listening hours fell 12% over the last month. How would you structure your investigation before proposing fixes?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-execution", "diagnosing-metrics", "metric-trees", "funnels"],
    relatedLessonIds: ["lesson-diagnose-drop", "lesson-metric-tree"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Confirm the metric is trustworthy.",
      "Localize when / where the drop appears.",
      "Segment users or platforms.",
      "Check recent product changes.",
      "Form ranked hypotheses.",
      "Propose next measurements.",
    ],
  },
  {
    id: "pq-exec-spotify-hours",
    title: "Metric Drop Deep Dive",
    prompt:
      "Daily listening hours fell 12% month-over-month on a streaming app. Walk through how you'd diagnose it with a metric tree and what you'd check first.",
    category: "execution-metrics",
    difficulty: "stretch",
    estimatedMinutes: 15,
    competencies: ["interview-execution", "metric-trees", "diagnosing-metrics"],
    relatedLessonIds: ["lesson-metric-tree", "lesson-diagnose-drop", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Draw or describe a metric tree.",
      "Separate volume vs engagement drivers.",
      "Call out data quality checks.",
      "Use segments intentionally.",
      "Connect findings to possible product causes.",
      "Avoid jumping straight to a feature.",
    ],
  },
  {
    id: "pq-sense-food-cancel",
    title: "Restaurant Cancellations",
    prompt:
      "You're PM for a food delivery app and restaurant cancellations suddenly increase. What would you examine, and how would you decide what to fix first?",
    category: "product-sense",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["interview-product-sense", "pain-points", "diagnosing-metrics", "prioritization"],
    relatedLessonIds: ["lesson-user-problem", "lesson-diagnose-drop", "lesson-prioritize"],
    relatedCreateTemplateIds: ["feature-proposal", "experiment-plan"],
    rubric: [
      "Clarify which cancellation rate and whose pain.",
      "Separate diner vs restaurant vs courier causes.",
      "Check operational vs product causes.",
      "Prioritize by impact and controllability.",
      "Define success / guardrails.",
    ],
  },
  {
    id: "pq-exec-food-cancel",
    title: "Cancellation Metrics",
    prompt:
      "Restaurant-initiated cancellations on a delivery platform rose from 3% to 5% of orders in two weeks. How do you investigate?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-execution", "diagnosing-metrics", "funnels"],
    relatedLessonIds: ["lesson-diagnose-drop", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Define the metric precisely.",
      "Check for logging or policy changes.",
      "Slice by city, cuisine, time, restaurant tier.",
      "Correlate with product / ops changes.",
      "Propose hypotheses and validation steps.",
    ],
  },
  {
    id: "pq-sense-design-habit",
    title: "Habit Loop for Reading",
    prompt:
      "Improve a mobile reading app so more people finish the books they start — without resorting to dark patterns.",
    category: "product-sense",
    difficulty: "stretch",
    estimatedMinutes: 15,
    competencies: ["interview-product-sense", "feature-ideation", "tradeoffs", "north-star-metrics"],
    relatedLessonIds: ["lesson-product-sense", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: [
      "Clarify success (finish rate vs time spent).",
      "Segment readers.",
      "Diagnose why books are abandoned.",
      "Propose ethical interventions.",
      "Call out tradeoffs and risks.",
      "Define metrics + guardrails.",
    ],
  },
  {
    id: "pq-exec-metric-drop",
    title: "Signup Completion Drop",
    prompt:
      "Signup completion on a fintech app dropped 15% after last Tuesday's release. How do you respond in the first 48 hours?",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["interview-execution", "diagnosing-metrics", "decision-making"],
    relatedLessonIds: ["lesson-diagnose-drop", "lesson-experimentation"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Stabilize / consider rollback.",
      "Verify data.",
      "Compare cohorts before/after.",
      "Inspect the changed funnel steps.",
      "Communicate status to stakeholders.",
    ],
  },
  {
    id: "pq-exec-choose-north-star",
    title: "North Star for a Study App",
    prompt:
      "You're PM for a flashcard study app used by college students. Propose a north-star metric, input metrics, and guardrails — and defend the choices.",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-execution", "north-star-metrics", "goals", "launch-metrics"],
    relatedLessonIds: ["lesson-choose-metrics", "lesson-metric-tree"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "State a north star tied to user value.",
      "Avoid vanity metrics.",
      "List actionable inputs.",
      "Include guardrails.",
      "Explain failure modes of the chosen metric.",
    ],
  },
  {
    id: "pq-exec-experiment",
    title: "Checkout Experiment",
    prompt:
      "Design an experiment to test whether showing delivery ETA before payment increases completed orders on a grocery app.",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-execution", "experimentation", "launch-metrics"],
    relatedLessonIds: ["lesson-experimentation", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Write a clear hypothesis.",
      "Choose primary + guardrail metrics.",
      "Describe exposure / assignment.",
      "Pre-commit a decision rule.",
      "Call out risks (gaming, seasonality).",
    ],
  },
  {
    id: "pq-strategy-enter-market",
    title: "New Market Entry",
    prompt:
      "A US-based tutoring marketplace wants to expand into Canada. How would you decide whether to enter, and what would you prioritize in the first six months?",
    category: "strategy",
    difficulty: "stretch",
    estimatedMinutes: 15,
    competencies: ["interview-strategy", "market-understanding", "positioning", "growth"],
    relatedLessonIds: ["lesson-strategy-tradeoffs", "lesson-prioritize"],
    relatedCreateTemplateIds: ["zero-to-one"],
    rubric: [
      "Clarify company goals / constraints.",
      "Assess market attractiveness.",
      "Compare build vs partner vs wait.",
      "Name explicit tradeoffs.",
      "Propose a sequenced first-year plan.",
      "Define leading indicators of success.",
    ],
  },
  {
    id: "pq-strategy-competitor",
    title: "Competitor Ships AI Summaries",
    prompt:
      "Your main competitor just launched AI-generated meeting summaries. You're PM for a notes app. What strategic options do you consider, and how do you choose?",
    category: "strategy",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["interview-strategy", "competitive-analysis", "positioning", "business-tradeoffs"],
    relatedLessonIds: ["lesson-strategy-tradeoffs", "lesson-prioritize"],
    relatedCreateTemplateIds: ["feature-proposal", "zero-to-one"],
    rubric: [
      "Avoid panic feature-matching.",
      "Restate your differentiation.",
      "Evaluate multiple strategic responses.",
      "Consider moat, cost, and user jobs.",
      "Recommend with tradeoffs.",
    ],
  },
  {
    id: "pq-strategy-roadmap-conflict",
    title: "Roadmap Conflict",
    prompt:
      "Engineering wants to pay down payment-system debt. Sales wants a custom dashboard for one enterprise prospect. How do you decide what ships this quarter?",
    category: "strategy",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-strategy", "prioritization", "roadmap-conflict", "stakeholder-management"],
    relatedLessonIds: ["lesson-prioritize", "lesson-stakeholders"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: [
      "Clarify company goals this quarter.",
      "Quantify or size each ask.",
      "Surface risk of delaying debt.",
      "Consider partial / time-boxed options.",
      "Communicate a clear decision.",
    ],
  },
  {
    id: "pq-behavioral-influence",
    title: "Influence Without Authority",
    prompt:
      "Tell me about a time you had to influence someone without formal authority. What did you do, and what happened?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-behavioral", "influence-without-authority", "stakeholder-management"],
    relatedLessonIds: ["lesson-stakeholders", "lesson-eng-design"],
    relatedCreateTemplateIds: [],
    rubric: [
      "Set context and stakes.",
      "Name the other person's incentives.",
      "Describe concrete influence tactics.",
      "Own the outcome (success or miss).",
      "Share a learning.",
    ],
  },
  {
    id: "pq-behavioral-saying-no",
    title: "Saying No",
    prompt:
      "Describe a time you said no to a stakeholder request. How did you handle it?",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 7,
    competencies: ["interview-behavioral", "saying-no", "prioritization"],
    relatedLessonIds: ["lesson-prioritize", "lesson-stakeholders"],
    relatedCreateTemplateIds: [],
    rubric: [
      "Explain why the ask conflicted with goals.",
      "Show empathy / alternatives.",
      "Describe the decision clearly.",
      "Cover the relationship aftermath.",
    ],
  },
  {
    id: "pq-behavioral-disagreement",
    title: "Design Disagreement",
    prompt:
      "Tell me about a disagreement with a designer or engineer. How did you resolve it?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-behavioral", "working-with-design", "working-with-engineering", "decision-making"],
    relatedLessonIds: ["lesson-eng-design", "lesson-stakeholders"],
    relatedCreateTemplateIds: [],
    rubric: [
      "State the disagreement without villains.",
      "Show how you sought understanding.",
      "Explain the decision framework used.",
      "Describe the outcome and follow-up.",
    ],
  },
  {
    id: "pq-behavioral-ambiguity",
    title: "Ambiguous Charter",
    prompt:
      "Tell me about a time you were given an ambiguous problem. How did you create clarity?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-behavioral", "ambiguity", "product-discovery", "decision-making"],
    relatedLessonIds: ["lesson-user-problem", "lesson-what-pm-does"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Describe the ambiguity.",
      "Show how you framed the problem.",
      "Mention stakeholders / constraints.",
      "Explain decisions under uncertainty.",
      "Share results.",
    ],
  },
  {
    id: "pq-estimation-marketplace",
    title: "Estimate Tutoring Sessions",
    prompt:
      "Estimate how many 1:1 tutoring sessions happen per week among undergraduates at a large US public university.",
    category: "estimation",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-estimation", "market-understanding"],
    relatedLessonIds: ["lesson-strategy-tradeoffs"],
    relatedCreateTemplateIds: [],
    hints: ["Start from students, then fraction who tutor, then frequency."],
    rubric: [
      "State assumptions clearly.",
      "Break into a logical structure.",
      "Use plausible ranges.",
      "Sense-check the result.",
      "Note what would change the estimate most.",
    ],
  },
  {
    id: "pq-estimation-rides",
    title: "Airport Rides",
    prompt:
      "Estimate the number of ride-hail trips to and from a major US airport on a typical weekday.",
    category: "estimation",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["interview-estimation"],
    relatedLessonIds: [],
    relatedCreateTemplateIds: [],
    rubric: [
      "Clarify scope (passengers, employees, etc.).",
      "Structure supply or demand side.",
      "Keep units consistent.",
      "Sanity-check against known facts.",
    ],
  },
  {
    id: "pq-technical-notifications",
    title: "Notification System Thinking",
    prompt:
      "Explain how you would think about building a notification system for a social study app (what can go wrong, what you'd ask engineering, what product decisions matter).",
    category: "technical",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["interview-technical", "working-with-engineering", "tradeoffs"],
    relatedLessonIds: ["lesson-eng-design", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Clarify product goals for notifications.",
      "Discuss channels / preferences / quiet hours.",
      "Mention reliability, latency, spam risks.",
      "Ask thoughtful engineering questions.",
      "Connect technical constraints to UX.",
    ],
  },
  {
    id: "pq-technical-search",
    title: "Search Relevance Basics",
    prompt:
      "You're PM for search on a marketplace for used textbooks. What would you explore to improve search relevance, and how would you partner with engineering?",
    category: "technical",
    difficulty: "stretch",
    estimatedMinutes: 12,
    competencies: ["interview-technical", "diagnosing-metrics", "working-with-engineering"],
    relatedLessonIds: ["lesson-eng-design", "lesson-diagnose-drop"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Define what “better search” means.",
      "Separate ranking vs retrieval vs UX.",
      "Propose evaluation methods.",
      "Respect data / labeling costs.",
      "Sequence experiments.",
    ],
  },
  {
    id: "pq-design-collab-onboarding",
    title: "Onboarding With Design",
    prompt:
      "Design and eng disagree: design wants a 5-step educational onboarding; eng wants a 1-step “skip to app.” You're the PM. How do you drive a decision?",
    category: "design-collab",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-design-collab", "working-with-design", "working-with-engineering", "experimentation"],
    relatedLessonIds: ["lesson-eng-design", "lesson-experimentation"],
    relatedCreateTemplateIds: ["experiment-plan", "prd"],
    rubric: [
      "Restate the shared user goal.",
      "Make tradeoffs explicit.",
      "Propose evidence (test, research, data).",
      "Avoid false compromise that serves no one.",
      "Define a decision owner and timeline.",
    ],
  },
  {
    id: "pq-sense-teardown-prompt",
    title: "Critique a Habit Tracker",
    prompt:
      "Critique a popular habit-tracking app. Who is it for, what works, where is friction, and what would you improve first?",
    category: "product-sense",
    difficulty: "warmup",
    estimatedMinutes: 10,
    competencies: ["interview-product-sense", "product-critique", "pain-points"],
    relatedLessonIds: ["lesson-segmentation", "lesson-user-problem"],
    relatedCreateTemplateIds: ["product-teardown"],
    rubric: [
      "Name a specific user.",
      "Describe the core job.",
      "Call out strengths with reasons.",
      "Identify concrete friction.",
      "Propose a prioritized improvement + metric.",
    ],
  },
  {
    id: "pq-sense-zero-to-one",
    title: "0→1 for Transfer Students",
    prompt:
      "Propose a 0→1 product that helps transfer students build a social and academic footing in their first term at a new university.",
    category: "product-sense",
    difficulty: "stretch",
    estimatedMinutes: 15,
    competencies: ["interview-product-sense", "zero-to-one", "user-segmentation", "feature-ideation"],
    relatedLessonIds: ["lesson-product-sense", "lesson-strategy-tradeoffs", "lesson-user-problem"],
    relatedCreateTemplateIds: ["zero-to-one"],
    rubric: [
      "Define the problem space tightly.",
      "Identify target user.",
      "Contrast current alternatives.",
      "State a sharp insight.",
      "Describe an MVP.",
      "Define validation plan.",
    ],
  },
  {
    id: "pq-strategy-pricing",
    title: "Freemium vs Paid",
    prompt:
      "A writing assistant for students is free with a 500-word daily cap. Would you introduce a paid plan now? How would you decide?",
    category: "strategy",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["interview-strategy", "business-tradeoffs", "growth", "positioning"],
    relatedLessonIds: ["lesson-strategy-tradeoffs", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["zero-to-one"],
    rubric: [
      "Clarify business goals.",
      "Assess willingness to pay signals.",
      "Consider packaging / gating carefully.",
      "Weigh growth vs monetization timing.",
      "Propose metrics for the decision.",
    ],
  },
  {
    id: "pq-exec-launch-metrics",
    title: "Launch Readiness",
    prompt:
      "You're about to launch a shared notes feature for a classroom app. What launch metrics and kill criteria would you set?",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["interview-execution", "launch-metrics", "experimentation"],
    relatedLessonIds: ["lesson-experimentation", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["experiment-plan", "prd"],
    rubric: [
      "Define primary success metric.",
      "Include guardrails (quality, abuse, performance).",
      "Set time window / sample.",
      "Predefine ship / iterate / rollback.",
    ],
  },
  {
    id: "pq-behavioral-miss",
    title: "A Miss",
    prompt:
      "Tell me about a product decision that didn't work out. What did you learn?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-behavioral", "decision-making", "experimentation"],
    relatedLessonIds: ["lesson-experimentation", "lesson-what-pm-does"],
    relatedCreateTemplateIds: [],
    rubric: [
      "Take ownership without self-flagellation.",
      "Explain the decision process at the time.",
      "Show what evidence was missing.",
      "Describe what changed afterward.",
    ],
  },
  {
    id: "pq-sense-prioritize-features",
    title: "Three Features, One Engineer",
    prompt:
      "You have one engineer for six weeks and three feature ideas for a campus housing app: roommate matching, maintenance tickets, and subletting listings. How do you choose?",
    category: "product-sense",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["interview-product-sense", "prioritization", "tradeoffs", "user-segmentation"],
    relatedLessonIds: ["lesson-prioritize", "lesson-segmentation"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: [
      "Clarify goal for the quarter.",
      "Compare impact / confidence / cost.",
      "Consider sequencing, not only pick-one.",
      "State what you will tell stakeholders.",
    ],
  },
  {
    id: "pq-estimation-storage",
    title: "Photo Storage Estimate",
    prompt:
      "Estimate how much photo storage a typical smartphone user adds per year. Explain your assumptions.",
    category: "estimation",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-estimation"],
    relatedLessonIds: [],
    relatedCreateTemplateIds: [],
    rubric: [
      "Define “typical”.",
      "Break into photos × size.",
      "Consider video separately if relevant.",
      "Sense-check against device capacities.",
    ],
  },

  // --- Enrichment: technical literacy, frameworks, closing questions ---
  {
    id: "pq-tech-b2b-b2c",
    title: "Explain B2B vs B2C",
    prompt:
      "Pick a real product. Explain whether it is primarily B2B, B2C, or B2B2C — and how that should change prioritization for the PM.",
    category: "technical",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["product-business-models", "interview-technical", "prioritization"],
    relatedLessonIds: ["lesson-b2b-b2c-ai", "lesson-tech-literacy-basics"],
    relatedCreateTemplateIds: ["product-teardown"],
    rubric: [
      "Identify buyer vs user.",
      "Name the sales / distribution motion.",
      "Connect model → prioritization implications.",
      "Avoid buzzwords without examples.",
    ],
  },
  {
    id: "pq-tech-frontend-backend",
    title: "Frontend vs Backend in PM Terms",
    prompt:
      "Explain frontend vs backend to a non-engineer classmate using a product example. Then name one tradeoff a PM might face between shipping UI polish and backend reliability.",
    category: "technical",
    difficulty: "warmup",
    estimatedMinutes: 7,
    competencies: ["frontend-backend", "technical-fluency", "tradeoffs"],
    relatedLessonIds: ["lesson-apis-frontend-backend", "lesson-tech-literacy-basics"],
    relatedCreateTemplateIds: [],
    rubric: [
      "Define frontend clearly.",
      "Define backend clearly.",
      "Use a concrete product example.",
      "State a real tradeoff.",
    ],
  },
  {
    id: "pq-tech-api-explain",
    title: "What Is an Api?",
    prompt:
      "Explain what an API is and why a PM should care — including one risk of depending on a third-party API.",
    category: "technical",
    difficulty: "warmup",
    estimatedMinutes: 7,
    competencies: ["apis-systems", "technical-fluency", "interview-technical"],
    relatedLessonIds: ["lesson-apis-frontend-backend", "lesson-reading-tech-docs"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Plain-language definition.",
      "Why PMs care (integrations, scope, risk).",
      "Mention a failure/limit risk.",
      "Stay accurate without fake jargon.",
    ],
  },
  {
    id: "pq-tech-lifecycle",
    title: "Map a Feature to the Lifecycle",
    prompt:
      "Take a feature idea. Walk it through discovery → definition → build → launch → learn. What artifact would you want at each stage?",
    category: "technical",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["product-lifecycle", "technical-fluency", "working-with-engineering"],
    relatedLessonIds: ["lesson-product-lifecycle", "lesson-what-pm-does"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Cover each stage.",
      "Name artifacts (research, PRD, tickets, metrics).",
      "Call out a stage teams often skip.",
    ],
  },
  {
    id: "pq-tech-read-docs",
    title: "Skim a Technical Doc Like a PM",
    prompt:
      "You are evaluating an integration. What would you look for first in the vendor’s API docs, and what three questions would you bring to engineering?",
    category: "technical",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["reading-tech-docs", "apis-systems", "working-with-engineering"],
    relatedLessonIds: ["lesson-reading-tech-docs", "lesson-apis-frontend-backend"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Mention limits / auth / errors.",
      "Tie findings to user impact.",
      "Ask engineering useful questions.",
      "Avoid pretending you’d implement it alone.",
    ],
  },
  {
    id: "pq-tech-eng-ambiguous",
    title: "Working With Eng on Ambiguity",
    prompt:
      "How would you work with engineering when the problem is still ambiguous — before requirements are crisp?",
    category: "technical",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["working-with-engineering", "ambiguity", "interview-technical"],
    relatedLessonIds: ["lesson-eng-design", "lesson-tech-literacy-basics"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: [
      "Separate discovery from build.",
      "Propose spikes / prototypes thoughtfully.",
      "Define decision criteria.",
      "Respect eng craft and time.",
    ],
  },
  {
    id: "pq-exec-rice-prioritize",
    title: "Rice a Prioritization Choice",
    prompt:
      "You have one engineer for a month and three ideas for a campus app: (1) push notifications for club events, (2) dark mode, (3) admin export for student orgs. Walk through a RICE-style comparison and pick one — naming assumptions.",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 12,
    competencies: ["rice-moscow", "prioritization", "interview-execution"],
    relatedLessonIds: ["lesson-rice-moscow", "lesson-prioritize"],
    relatedCreateTemplateIds: ["feature-proposal", "prd"],
    rubric: [
      "Define Reach / Impact / Confidence / Effort inputs.",
      "State assumptions explicitly.",
      "Make a clear pick.",
      "Name what you defer and why.",
    ],
  },
  {
    id: "pq-exec-moscow-scope",
    title: "Moscow a Release",
    prompt:
      "Scope a two-week release for “study group finder.” Use Must / Should / Could / Won’t. Defend the cut line.",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["rice-moscow", "prioritization", "saying-no"],
    relatedLessonIds: ["lesson-rice-moscow"],
    relatedCreateTemplateIds: ["prd"],
    rubric: [
      "Fill all four MoSCoW buckets.",
      "Must list is truly minimal.",
      "Explain the Won’t rationale.",
    ],
  },
  {
    id: "pq-exec-user-story",
    title: "Write a User Story",
    prompt:
      "Write three user stories for improving onboarding on a budgeting app. Keep them free of UI prescriptions.",
    category: "execution-metrics",
    difficulty: "warmup",
    estimatedMinutes: 8,
    competencies: ["okrs-jtbd", "user-problems", "user-research-basics"],
    relatedLessonIds: ["lesson-okrs-jtbd", "lesson-user-problem"],
    relatedCreateTemplateIds: ["prd", "feature-proposal"],
    rubric: [
      "Use clear As a / I want / so that shape.",
      "No sneaky UI specs.",
      "Stories are testable.",
    ],
  },
  {
    id: "pq-exec-okr-draft",
    title: "Draft an OKR",
    prompt:
      "Draft one Objective and three Key Results for a PM owning retention on a note-taking app used by students.",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["okrs-jtbd", "goals", "north-star-metrics"],
    relatedLessonIds: ["lesson-okrs-jtbd", "lesson-choose-metrics"],
    relatedCreateTemplateIds: ["study-plan"],
    rubric: [
      "Objective is directional not a metric.",
      "KRs are measurable.",
      "Avoid vanity shipping KRs.",
    ],
  },
  {
    id: "pq-exec-speed-vs-scale",
    title: "Speed vs Scalability Tradeoff",
    prompt:
      "Explain a tradeoff between shipping speed and scalability for a feature that suddenly goes viral on campus. What would you choose in week one vs month three?",
    category: "execution-metrics",
    difficulty: "standard",
    estimatedMinutes: 10,
    competencies: ["tradeoffs", "apis-systems", "interview-execution"],
    relatedLessonIds: ["lesson-apis-frontend-backend", "lesson-rice-moscow"],
    relatedCreateTemplateIds: ["experiment-plan"],
    rubric: [
      "Define both sides of the tradeoff.",
      "Time-phase the decision.",
      "Mention risk / cost.",
      "Avoid false “we’ll do both fully now”.",
    ],
  },
  {
    id: "pq-stakeholder-update",
    title: "Stakeholder Update",
    prompt:
      "Write a short stakeholder update after user research showed your planned feature won’t solve the target user’s problem. Include decision and ask.",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["stakeholder-management", "user-research-basics", "executive-communication"],
    relatedLessonIds: ["lesson-user-research-stakeholders", "lesson-stakeholders"],
    relatedCreateTemplateIds: ["feature-proposal"],
    rubric: [
      "Lead with decision.",
      "Cite evidence briefly.",
      "Clear ask / next step.",
      "Tone is direct not defensive.",
    ],
  },
  {
    id: "pq-behavioral-strengths-story",
    title: "Non-technical Strength Story",
    prompt:
      "Tell a story from a non-engineering experience (work, leadership, customer-facing, domain) and translate it into a PM skill with a concrete decision.",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["non-technical-strengths", "interview-behavioral", "decision-making"],
    relatedLessonIds: ["lesson-non-technical-strengths", "lesson-weeks-1-3-roadmap"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: [
      "Specific situation.",
      "Explicit PM skill translation.",
      "Decision + outcome.",
      "No apology framing.",
    ],
  },
  {
    id: "pq-closing-success",
    title: "Closing: What Does Success Look Like?",
    prompt:
      "Practice asking — naturally — what success looks like in the role. Then outline how you’d listen and follow up.",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 6,
    competencies: ["interview-closing", "interview-behavioral"],
    relatedLessonIds: ["lesson-interview-closing"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: [
      "Question sounds conversational.",
      "Shows interest in outcomes not perks.",
      "Notes how you’d use the answer.",
    ],
  },
  {
    id: "pq-closing-challenge",
    title: "Closing: Biggest Challenge",
    prompt:
      "Practice asking what the biggest challenge would be for someone stepping into this role. How would you respond if they name something hard?",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 6,
    competencies: ["interview-closing", "interview-behavioral"],
    relatedLessonIds: ["lesson-interview-closing"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: [
      "Question is respectful.",
      "Plan a thoughtful response.",
      "Avoid defensiveness.",
    ],
  },
  {
    id: "pq-closing-feedback",
    title: "Closing: Confidence / Pause Questions",
    prompt:
      "Practice two brave closing questions: (1) whether anything would increase their confidence in you, and (2) whether anything in your background gives them pause. When would you use each?",
    category: "behavioral",
    difficulty: "standard",
    estimatedMinutes: 8,
    competencies: ["interview-closing", "interview-behavioral", "non-technical-strengths"],
    relatedLessonIds: ["lesson-interview-closing", "lesson-non-technical-strengths"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: [
      "Rephrase in your own voice.",
      "Note rapport conditions.",
      "Plan calm follow-ups.",
      "Don’t sound interrogative.",
    ],
  },
  {
    id: "pq-closing-culture",
    title: "Closing: Team & Culture",
    prompt:
      "Practice asking what qualities the strongest person in this role demonstrates — and why the interviewer likes working here. Make both sound genuine.",
    category: "behavioral",
    difficulty: "warmup",
    estimatedMinutes: 6,
    competencies: ["interview-closing", "interview-behavioral"],
    relatedLessonIds: ["lesson-interview-closing"],
    relatedCreateTemplateIds: ["interview-prep"],
    rubric: [
      "Both questions feel natural.",
      "Tied to learning not flattery.",
      "Ready to connect answer to your strengths.",
    ],
  },
];
